name: Java CI with Maven

# it doesn't update the protobuf files and doesn't create new Java bindings
# it does compile updated Java bindings if they are created and pushed somewhere else

on:
  [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven
        server-id: tbb-github
        server-username: GITHUB_USER_REF
        server-password: GITHUB_TOKEN_REF
    - name: Build with Maven
      run: mvn -B -U install --file pom.xml
      env:
        GITHUB_USER_REF: noone
        GITHUB_TOKEN_REF: ${{ secrets.PACKAGE_ACCESS_TOKEN}}
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: protobuf-jar
        path: derec-protobuf/target/derec-protobuf-0.9-SNAPSHOT.jar
